# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: node:16


pipelines:
  default:
    - step:
        name: Build
        script:
          - npm install
  branches:
    release/*:
      - parallel:
          - step:
              name: Heroku Deploy
              script:
                - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH:master --force